<Project>
  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)LICENSE.txt" Link="LICENSE.txt"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
    <None Include="$(MSBuildThisFileDirectory)NOTICE.md" Link="NOTICE.md"
          CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest"
          ExcludeFromSingleFile="true" />
  </ItemGroup>
</Project>
